server:
  port: 8081

spring:
  datasource:
    url: jdbc:firebirdsql://localhost:3050/C:/Users/gleb/Desktop/PERSON.FDB?encoding=UTF8
    username: sysdba
    password: Root
  driver-class-name: org.firebirdsql.jdbc.FBDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.FirebirdDialect
    properties:
      hibernate.connection.characterEncoding: UTF8
